runtime: nodejs20
instance_class: F1

env_variables:
  PROJECT_ID: 'tw-maxchens-sandbox'
  GCS_BUCKET_NAME: 'meeting-audio-maxtest'
  # 例如：us-central1, asia-east1, etc.
  LOCATION: 'us-central1'

  # 明確設置為生產環境
  NODE_ENV: 'production'
  DEPLOYMENT_ENV: 'production'
  
  # 生產環境的 Base URL
  NEXT_PUBLIC_GOOGLE_CLIENT_ID: '143859697876-kpgc7afaebthub6toe3o7gafcr436gfd.apps.googleusercontent.com'
  NEXT_PUBLIC_BASE_URL: 'https://meeting.hkmci.com.tw'

handlers:
  - url: /.*
    secure: always
    redirect_http_response_code: 301
    script: auto

# 自動擴展配置 - 內部應用使用，低流量
automatic_scaling:
  min_instances: 0
  max_instances: 2  # 允許擴展到更多實例
  target_cpu_utilization: 0.75
  target_throughput_utilization: 0.75
  max_concurrent_requests: 10  # 減少並發請求數量
  min_pending_latency: 5000ms  # 更寬容的延遲設定
  max_pending_latency: 10000ms