runtime: nodejs20
instance_class: F2

env_variables:
  GOOGLE_CLOUD_PROJECT_NUMBER: "143859697876"

handlers:
  - url: /.*
    secure: always
    redirect_http_response_code: 301
    script: auto

# 自動擴展配置 - 內部應用使用，低流量
automatic_scaling:
  min_instances: 0
  max_instances: 2  # 允許擴展到更多實例
  target_cpu_utilization: 0.75
  target_throughput_utilization: 0.75
  max_concurrent_requests: 10  # 減少並發請求數量
  min_pending_latency: 5000ms  # 更寬容的延遲設定
  max_pending_latency: 10000ms